- cloudformation/openondemand.yml
*Description of changes:* Add versioning to S3 bucket and yamllint cloudformation file
> Update S3 Bucket to enable versioning

- README.md
- cloudformation/openondemand.yml
- scripts/install_ood.sh
- scripts/join_domain.sh
- scripts/pcluster_head_node.sh
- scripts/pcluster_worker_node.sh
*Issue #, if available:*
Update the solution so that OOD Portal uses SSSD instead of joining the domain, simplifying the solution slightly 
> Feature no domain join

- cloudformation/openondemand.yml
- scripts/deploy.sh
> Regex + Deploy Script

- scripts/create_sample_pcluster_config.sh
*Description of changes:* Updates `create_sample_pcluster_config.sh` to include setting the home directory to the shared drive
> Update PCLuster sample script to include the shared home directory

- cloudformation/openondemand.yml
- scripts/create_sample_pcluster_config.sh
*Issue #, if available:* 23
*Description of changes:* Update AMI IDs based on this source: https://www.centos.org/download/aws-images/
> Fixit ubuntu version

- .gitignore
- cloudformation/openondemand.yml
- scripts/configure_cloudwatch_metrics.sh
- scripts/configure_mkhomedir.sh
- scripts/configure_slurm_accounting.sh
- scripts/install_munge.sh
- scripts/install_ood.sh
- scripts/install_slurm.sh
- scripts/install_spack.sh
- scripts/mount_efs.sh
- scripts/pcluster_head_node.sh
- scripts/pcluster_worker_node.sh
- scripts/pcluster_worker_node_desktop.sh
* Upgrade Open OnDemand to v3.0.0
* Upgrade Slurm version to 23.02.2
* Changed base AMI to Ubuntu 22.04.3
* IAM Policy updates to address SSM patching failing
* Updated pcluster scripts to leverage IMDSv2
* Changed Aurora DB Instance to db.t3.medium to address db engine to instance class compatibility
*Issue #, if available:*
> Upgrading Open OnDemand to 3.0.0

- README.md
- cloudformation/openondemand.yml
- scripts/configure_login_nodes.sh
- scripts/install_ood.sh
- scripts/upload_pcluster_configs.sh
* Added a new script to configure ParallelCluster Login Nodes
* Add security group to allow outbound connection to Login Nodes
* Bug fixes:
* Fix timeout to be applied to ALB
* Fix ood_install script to ensure `.bashrc` and `.bash_profile` are created when new users are added
> Login Nodes and minor bug fixes

- README.md
- scripts/configure_pam_slurm_adopt.sh
- scripts/install_ood.sh
- scripts/upload_pcluster_configs.sh
*Description of changes:* Added the following updates:
* Added a new script to configure `pam_slurm_adopt`
* Added instructions to README for enabling `pam_slurm_adopt`
* Added a fix to add_user to create minimal `bashrc` and `bash_profile`
> Adding pam_slurm_adopt and fixes to add_user script

- README.md
- cloudformation/openondemand.yml
- scripts/configure_cluster_for_ood.sh
- scripts/create_sample_pcluster_config.sh
- scripts/install_ood.sh
- scripts/install_slurm.sh
- scripts/mount_efs.sh
- scripts/pcluster_worker_node_desktop.sh
* Fixed `scripts/create_sample_pcluster_config.sh` to add `MungeKeySecretId` to the cluster config. 
* Updated AL2023 AMI
* Changed EFS installation to no longer build from github repo
* Added troubleshooting steps when job submission fails after adding a ParallelCluster
> Fix create_sample_pcluster_config and other minor updates

- README.md
*Issue #48*
Fixing quick launch links from README
> Fixing quick launch links

- README.md
> Removing quick launch icon

- README.md
- assets/cloudformation/infra.yml
- assets/cloudformation/ood.yml
- assets/cloudformation/ood_full.yml
- assets/cloudformation/slurm_accounting_db.yml
- deploy-assets.sh
- scripts/create_sample_pcluster_config.sh
- scripts/pcluster_head_node.sh
*Description of changes:* Separating out Slurm accounting database from **OOD** stack.  
> Splitting out Slurm Accounting Database from main stack

- assets/cloudformation/ood.yml
*Description of changes:* Fixing output value for AD secret
> Fixing AD secret

- assets/cloudformation/ood_full.yml
Fixing CloudFormation references for SlurmAccountingDB stack
> Ood full dbsecretid fix

- .pre-commit-config.yaml
- scripts/install_ood.sh
Upgrading solution to Open OnDemand v4.0
> Upgrade to Open OnDemand v4.0

- README.md
Update slurm configuration readme to include an example.
> Updated slurm configuration management details

- assets/cloudformation/ood_full.yml
fix: Fix `ood_full` deployment issues related to EFS and SlurmVersion.
> Bugfixes for ood_full deployment pattern

- scripts/install_spack.sh
Fixed the `install_spack` script to work on AL2023. 
> Fixed install_spack script to work on AL2023

- scripts/install_ood.sh
*Issue #, if available:*
Fixing myjobs session
> fix: Fixing myjobs session

- README.md
- assets/cloudformation/ood.yml
- assets/cloudformation/ood_full.yml
- deploy-assets.sh
- scripts/deploy_pcs.sh
- Fix missing parameters in `ood_full.yml`
- simplified cfn-bootstrap installation
- fixes to `deploy_pcs.sh` to check SLURM_VERSION 
> Fixes to OOD_FULL deployment
